version: '3'
services:

  kafka-consumer:
    container_name: kafka-consumer
    build: ./kafka-consumer
    depends_on:
      - kafka-2
    ports:
      - "8080:8080"
    entrypoint: /bin/sh
    command: >
      -c "
      while ! (nc -z kafka-2 9092 ); do sleep 5; echo 'Waiting for kafka-2 services to start-up...'; done;
      java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8787,suspend=n -jar -Dspring.profiles.active=docker /app.jar
      "

  kafka-producer:
    container_name: kafka-producer
    build: ./kafka-producer
    depends_on:
      - kafka-2
    ports:
      - "8083:8083"
    entrypoint: /bin/sh
    command: >
      -c "
      while ! (nc -z kafka-2 9092 ); do sleep 5; echo 'Waiting for kafka-2 services to start-up...'; done;
      java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8787,suspend=n -jar -Dspring.profiles.active=docker /app.jar
      "

  zookeeper-2:
    image: confluentinc/cp-zookeeper:5.0.0
    hostname: zookeeper-2
    container_name: zookeeper-2
    ports:
      - "2181:2181"
    env_file:
      - config/zookeeper.env
    healthcheck:
      test: /bin/sh -c '[ \"imok\" = \"$$(echo ruok | nc -w 1 127.0.0.1 2181)\" ]' || exit 1
      interval: 1m
    volumes:
      - zookeeper-2-data:/var/lib/zookeeper/data/
      - zookeeper-2-log:/var/lib/zookeeper/log/

  kafka-2:
    image: confluentinc/cp-kafka:5.0.0
    hostname: kafka-2
    container_name: kafka-2
    stop_grace_period: 5m
    depends_on:
      - zookeeper-2
    ports:
      - "9092:9092"
      - "29092:29092"
    env_file:
      - config/kafka.env
    volumes:
      - kafka-2-data:/var/lib/kafka/data/

  schema-registry-2:
    image: confluentinc/cp-schema-registry:5.0.0
    hostname: schema-registry-2
    container_name: schema-registry-2
    depends_on:
      - zookeeper-2
      - kafka-2
    ports:
      - "8081:8081"
    env_file:
      - config/schema-registry.env

volumes:
  zookeeper-2-data:
  zookeeper-2-log:
  kafka-2-data: